### ISSUE TITLE
Layer1 api should not be shipped with adapter

### ISSUE THREAD

**Issue by svyatoslav-toder** [aris-i/okex-bookmap-adapter#1]
Jar that is built by "mvn package" includes bookmap classes.
It isn't going to help in any case - if api was changed in incompatible way this will not work anyway.
Similarly, you might want to get rid of some dependencies that are already in Bookmap (which is not mandatory, but will make module smaller).

**Comment by svyatoslav-toder** [comment]
Just to explain in more depth - the main reason why Bookmap classes should not be part of the jar is that some are not going to load, breaking the autodiscovery mechanism (the one allowing to just drop adapter into the folder)

**Comment by aris-i** [comment]
Thanks for submitting this issue and for your detailed explantion.
 
This has been fixed on this commit:  20b9f3e408998032db135dadd6d2751f2b066152

Let me know if I missed anything.

**Comment by svyatoslav-toder** [comment]
Looks good. At least now it can be loaded via autodiscovery into the internal version that will be released a bit later.
