### ISSUE TITLE
Connecting to unconfigured adapter causes exception

### ISSUE THREAD

**Issue by svyatoslav-toder** [aris-i/okex-bookmap-adapter#2]
It's
`java.lang.ArrayIndexOutOfBoundsException: 1
	at com.stableapps.okexbookmapadapter.bm.OkexRealTimeProvider.login(OkexRealTimeProvider.java:162)
`
I recommend to complain about invalid configuration with onLoginFailed callback instead

**Comment by aris-i** [comment]
Fixed as of commit c336ea2099fb5382bfcf18bedab51ca6e30433a2

**Comment by svyatoslav-toder** [comment]
Seems to work fine
