### ISSUE TITLE
Connection is not recovered after long disconnection

### ISSUE THREAD

**Issue by svyatoslav-toder** [aris-i/okex-bookmap-adapter#3]
I see that you limited reconnection attempts. I'm not sure why (if you don't need to - I'd recommend to remove the limit), but if you want adapter to give up after N attempts - at least let user know via `Layer1ApiAdminListener#onSystemTextMessage` that connection will not be restored and he has to reconnect manually. But I'd suggest to recover when possible - imagine network going down for few minutes in the middle of a night after user left Bookmap to record the data.

**Comment by aris-i** [comment]
Fixed as of 7b61c5fbadeec2248758c2b7d07fcd0afdd54e70.  It will retry indefinitely every 5 seconds until connection is restored.
