### ISSUE TITLE
Realized P&L is only loaded after actions with orders

### ISSUE THREAD

**Issue by svyatoslav-toder** [aris-i/okex-bookmap-adapter#5]
- make sure your p&l is non-zero
- exit
- start&connect
- do nothing for a minute. It will keep being displayed as 0
- send an order (no need for it to execute, e.g. just send a limit far from BBO)
- total P&L will get populated within about a second or two

I would expect it to be populated from start.

**Comment by aris-i** [comment]
Fixed as of da86e4f6ec54f02380755198d8315fc72f682733.  This was a multi-threading race condition.
